export async function GET() {
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>https://creatikai.com/</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/resourses/contact-us</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/resourses/about-us</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/training/ai-automation</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/training/digital-marketing</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/services/bussiness-enhance</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/services/video-creation</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/services/content-creation</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/training/ai-machine-learning</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/training/fullstack-web-development</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/industry/education</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/industry/real-estate</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/industry/healthcare</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/resourses/why-choose-us</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/blog</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/services/bussiness-automation</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/services/lead-automation</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/services/workflow-automation</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/services/ai-chatbot</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/services/ai-personal-assistant</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/services/ai-tools</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/industry/technology</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/industry/travel-tourism</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/industry/consumer-goods-retail</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/training/social-media</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/training/google-ads</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/products/calling-agent</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/products/content-creation-agent</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/products/seo-content-agent</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/products/follow-up-agent</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/products/data-mining-agent</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/products/campaign-automation</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/products/lead-capture-agent</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/products/lead-qualifiction-agent</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/products/property-maching-agent</loc>
<lastmod>2026-08-10</lastmod>
</url>
<url>
<loc>https://creatikai.com/products/social-media-agent</loc>
<lastmod>2026-08-10</lastmod>
</url>
</urlset>`;

  return new Response(xml, {
    headers: {
      "Content-Type": "application/xml",
    },
  });
}