import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import LayoutWrapper from "@/components/layoutwrapper/layoutwrapper";
import { AuthProvider } from "@/context/AuthContext";
import NewsletterPopup from "@/components/newsLetterPopup";


export const metadata: Metadata = {
  title: "Creatikai | with creative mind",
  description: "Generated by creative ideas",
    manifest: "/manifest.json",
   

  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "CreatikAI",
  },

};

export const viewport: Viewport = {
  themeColor: "#1e88e5",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
    <LayoutWrapper>
        {children}
      
</LayoutWrapper>
</AuthProvider>
        </body>
    </html>
  );
}
